<h2><a href="<?php echo $this->user['url']; ?>" class="btn"><?php echo $this->user['logText']; ?></a>
<?php if(isset($this->user['text']))
{
    echo '<br />'.$this->user['text'];
} ?>
</h2>

<?php
if(isset($this->user['userProfile']) && is_array($this->user['userProfile'])):
?>
<div style="text-align:left; width:960px; margin:0 auto;">
    <h3>Your latest Facebook Activity is...</h3>
    <p class="post"><?php echo $this->user['userProfile']['fullMsg'];?></p>


    <h3>You will post...</h3>
    <h4>Remember, we can only text 160 chars, so your text message will look like this...</h4>

    <img src="https://graph.facebook.com/<?php echo $this->user['userProfile']['id']; ?>/picture?type=large" style="float:left; margin-right:20px;">
    <div style="float:left; width:700px;">
        <p class="post"><?php echo $this->user['userProfile']['msg']; ?></p>

        <?php
            echo $this->form;
        ?>
    </div>
</div>
<?php endif; ?>
